/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/mnt/d/Nim/lib -o /mnt/d/pyvmomi/sample/nimcache/stdlib_varints.c.o /mnt/d/pyvmomi/sample/nimcache/stdlib_varints.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
N_LIB_PRIVATE N_NIMCALL(void, stdlib_varintsInit000)(void) {
}

N_LIB_PRIVATE N_NIMCALL(void, stdlib_varintsDatInit000)(void) {
}

